home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('home', views.index, name='index'),
    path('contact', views.contact_form, name='contact'),
    path('login', views.login_form),
    path('join', views.join_form),
    path('logout', views.login_out),

]

mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mysite import settings

urlpatterns = [
    path('', include('home.urls')),
    path('product/', include('product.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('order/', include('order.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from order import views
app_name = 'order'
urlpatterns = [
    path('', views.index, name='index'),
    path('shopcart', views.shop_cart_list, name='shopcart'),
    path('addtocart/<int:proid>', views.shop_cart_add, name='addtocart'),
    path('deletefromcart/<int:id>', views.shop_cart_delete, name='deletefromcart'),
    path('checkout', views.shop_cart_checkout, name='checkout'),
    path('detail/<int:id>', views.order_detail, name='orderdetail'),

]

order/models.py
from django.contrib.auth.models import User
from django.db import models

from django.forms import ModelForm, TextInput
from product.models import Product


class ShopCart(models.Model):

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.OneToOneField(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField()

    def __str__(self):
        return self.product

    @property
    def amount(self):
        return (self.quantity * self.product.price)


class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']
        widgets = {
            'quantity': TextInput(attrs={'class': 'input', 'type': 'number', 'value': '1'}),
        }


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preparing', 'Preparing'),
        ('OnShippping', 'OnShippping'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),

    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=10)
    surname = models.CharField(max_length=10)
    address = models.CharField(max_length=150)
    city = models.CharField(max_length=20)
    phone = models.CharField(max_length=20)
    total = models.FloatField()
    note = models.TextField(null=True, default="")
    status = models.CharField(choices=STATUS, default='New', max_length=15)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['name', 'surname', 'address', 'city', 'phone']
        widgets = {
            'name': TextInput(attrs={'class': 'text'}),
            'surname': TextInput(attrs={'class': 'text'}),
            'address': TextInput(attrs={'class': 'text'}),
            'city': TextInput(attrs={'class': 'text'}),
            'phone': TextInput(attrs={'class': 'text'}),
        }


class OrderDetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()  # floatfileddıbaşta
    price = models.FloatField()
    total = models.FloatField(default=0)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product

order/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from order.models import ShopCartForm, ShopCart, OrderForm, Order, OrderDetail


@login_required(login_url='/login')
def index(request):
    current_user = request.user
    orders = Order.objects.all().filter(user_id=current_user.id)

    context = {
                'page': 'orders',
                'orders': orders,
                }
    return render(request, 'order_list.html', context)


@login_required(login_url='/login')
def shop_cart_list(request):

    current_user = request.user
    shopcart = ShopCart.objects.all().filter(user_id=current_user.id)
    carttotal = 0

    for rs in shopcart:
        carttotal+=rs.quantity * rs.product.price
    context = {'page': 'cart',
               'shopcart': shopcart,
               'carttotal': carttotal,

               }
    return render(request, 'shop_cart_list.html', context)


@login_required(login_url='/login')
def shop_cart_add(request, proid):
    url1 = "/product/"+str(proid)+"/"
    url = request.META.get('HTTP_REFERER')
    form = ShopCartForm(request.POST or None)
    if request.method == 'POST':

        if form.is_valid():
            current_user = request.user
            quantity = form.cleaned_data['quantity']
            try:
                q1 = ShopCart.objects.get(user_id=current_user.id, product_id=proid)
            except ShopCart.DoesNotExist:
                q1 = None
            if q1 != None:
                q1.quantity = q1.quantity + quantity
                q1.save()
            else:
                data = ShopCart(user_id=current_user.id, product_id=proid, quantity=quantity)
                data.save()
            request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count()
            messages.success(request, "product added to cart")
            return HttpResponseRedirect(url)

    return HttpResponseRedirect(url1)


@login_required(login_url='/login')
def shop_cart_delete(request, id):
    url = request.META.get('HTTP_REFERER')
    ShopCart.objects.filter(id=id).delete()
    messages.success(request, "Product deleted from cart.")
    return HttpResponseRedirect(url)


@login_required(login_url='/login')
def shop_cart_checkout(request):
    current_user = request.user
    shopcart =ShopCart.objects.all().filter(user_id=current_user.id)
    carttotal=0

    form = OrderForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():

            data = Order()  # formdan gelen verileri eslestiriyoruz
            data.name = form.cleaned_data['name']
            data.surname = form.cleaned_data['surname']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.phone = form.cleaned_data['phone']
            data.to = form.cleaned_data['name']
            data.user_id = current_user.id
            data.total = carttotal
            data.save()  # siparis bilgilerini kaydediyoruz veritabanina

            # save shopcart items to order detail items
            for rs in shopcart:
                detail = OrderDetail()
                detail.order_id = data.id
                detail.product_id = rs.product_id
                detail.user_id = current_user.id
                detail.quantity = rs.quantity
                detail.price = rs.product.price
                detail.total = rs.amount
                detail.save()
            ShopCart.objects.filter(user_id=current_user.id).delete()
            request.session['cart_items'] = 0
            messages.success(request, "Order has been completed. Thank you")
            return HttpResponseRedirect("/order")

    context = {
            'page': 'checkout',
            'shopcart': shopcart,
            'carttotal': carttotal,
            }
    return render(request, 'shop_cart_checkout.html', context)


@login_required(login_url='/login')
def order_detail(request, id):

    order = Order.objects.get(pk=id)
    items = OrderDetail.objects.all().filter(order=id)

    context = {
        'page': 'detail',
        'order': order,
        'items': items,
    }

    return render(request, 'order_detail.html', context)

order/templates/order_detail.html
{% extends "homebase.html" %}

{% block title %} order list  {% endblock %}

{% block body   %}

<h1>order list</h1>

<section id="cart_items">
    <div class="container">
        <div class="breadcrumbs">
            <ol class="breadcrumb">
                <li><a href="#">Home</a></li>
                <li class="active">Shopping Cart</li>
            </ol>
        </div>
        <div class="table-responsive cart_info">
            <table class="table table-condensed">
                <thead>
                <tr>
                    <th>Name</th> <td>{{ order.name }}</td>
                </tr>
                <tr>
                    <th>Surname</th> <td>{{ order.surname }}</td>
                </tr>
                <tr>
                    <th>Address</th> <td>{{ order.address }}</td>
                </tr>
                <tr>
                    <th>City</th> <td>{{ order.city }}</td>
                </tr>
                <tr>
                    <th>City</th> <td>{{ order.phone }}</td>
                </tr>
                <tr>
                    <th>Date</th> <td>{{ order.create_at }}</td>
                </tr>
                <tr>
                    <th>Note</th> <td>{{ order.note }}</td>
                </tr>
                <tr>
                    <th>Status</th> <td>{{ order.status }}</td>
                </tr>
                </thead>


                <table class="table">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Product Name</th>
                        <th>Sale Price</th>
                        <th>Quantity</th>
                        <th>Amount</th>
                        <th>Actions</th>
                    </tr>
                    </thead>

                    <tbody>

                    {% for rs in items %}
					carttotal+=rs.quantity * rs.product.price
                    <tr>
                        <td>{{ rs.price }}</td>
                        <td>{{ rs.id }}</td>
                        <td>{{ rs.product.title }}</td>
                        <td>{{ rs.quantity }}</td>
                        <td>{{ rs.amount }} TL</td>
                        <td>{{ rs.total }} TL</td>
                        <td>
                            <a href="/order/deletefromcart/{{ rs.id }}">Delete</a>
                        </td>
                        <td colspan="5" ><b> toplam alışveriş tutarı :{{ rs.total }} TL</b>
                    </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </table>
        </div>
    </div>
</section> <!--/#cart_items-->
{% endblock %}

order/templates/order_list.html
{% extends "homebase.html" %}

{% block title %} order detail  {% endblock %}

{% block body   %}

<h1>order list</h1>

            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
                {% endfor %}

            {% endif %}

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Product Name</th>
                <th>Sale Price</th>
                <th>Quantity</th>
                <th>Amount</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>


        {% for rs in orders %}
            carttotal+=rs.quantity * rs.product.price
            <tr>
                <td class="details"><strong>{{rs.name }} {{ rs.surname }}</strong></td>
                <td class="price text-center"><strong>{{rs.create_at}}</strong></td>
                <td class="price text-center"><strong>{{rs.phone }}</strong></td>
                <td class="qty text-center"><strong>{{rs.city }}</strong></td>
                <td class="total text-center"><strong class="primary-color">${{rs.total}}</strong></td>
                <td class="total text-center"><strong>{{rs.status }}</strong></td>
                <td class="text-right"><a href="/order/detail/{{ rs.id }}"><strong>Detail</strong></a></td>
            </tr>
        {% endfor %}

        <td colspan="5" ><b> toplam alışveriş tutarı :{{ carttotal }} TL</b>
        </tbody>
    </table>

        <div class="pull-right">
            <a href="/order/checkout" class="btn btn-default check_out">Check Out</a>
        </div>


{% endblock %}

order/templates/shop_cart_checkout.html
{% extends "homebase.html" %}

{% block title %} shop cart checkout  {% endblock %}

{% block body %}

<section id="cart_items">
		<div class="container">
			<div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="/">Home</a></li>
				  <li class="active">Check out</li>
				</ol>
			</div><!--/breadcrumbs-->

			<div class="register-req">
				<p>Please use Register And Checkout to easily get access to your order history, or use Checkout as Guest</p>
			</div><!--/register-req-->

			<div class="shopper-informations">
				<div class="row">
					<div class="col-sm-5 clearfix">
						<div class="bill-to">
							<p>Shopper Information</p>
							<div class="form-one">
								<div class="form-one">
									<form id="checkout-form1" name="order" class="clearfix"  method="post">
										{% csrf_token %}
										<input class="text" type="text" name="name" placeholder="First Name" required id="id_name" value="{{ user.first_name }}" >
										<input class="text" type="text" name="surname" placeholder="Last Name" required id="id_surname" value="{{ user.last_name }}">
										<input class="text" type="text" name="address" placeholder="Address" required id="id_address">
										<input class="text" type="text" name="city" placeholder="City" required id="id_city">
										<input class="text" type="tel" name="phone" placeholder="Telephone" required id="id_phone">
										<button type="submit" class="btn btn-primary">Complete Order</button>
									</form>
								</div>
								<div class="form-two">

									<form id="checkout-form2" name="order" action="/order/" class="clearfix" method="post">
										{% csrf_token %}
										<input class="text" type="text" name="first-name" placeholder="Card Name" >
										<input class="text" type="text" name="last-name" placeholder="Card Number" >
										<input class="text" type="date" name="email" placeholder="Date: YYYY/MM/DD" >
										<input class="text" type="text" name="address" placeholder="Code" >
										<input class="text" type="text" name="address" placeholder="Code" value="Order Total: $ {{ carttotal }}" readonly >
									</form>
             					 </div>
							</div>
						</div>
					</div>
					<div class="col-sm-4">
						<div class="order-message">
							<p>Shipping Order</p>
							<textarea name="message"  placeholder="Notes about your order, Special Notes for Delivery" rows="16"></textarea>
							<label><input type="checkbox"> Shipping to bill address</label>
						</div>
					</div>
				</div>
			</div>
			<div class="review-payment">
				<h2>Review</h2>
			</div>

            <form id="checkout-form" name="order" class="clearfix" method="post">
				<div class="table-responsive cart_info">
                <table class="table table-condensed">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Product Name</th>
                        <th>Sale Price</th>
                        <th>Quantity</th>
                        <th>Amount</th>
                        <th>Actions</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for rs in shopcart %}
                    <tr>
						<td>{{rs.product.price}}</td>
                        <td>{{ rs.id }}</td>
                        <td>{{ rs.product.title }}</td>
                        <td>{{ rs.quantity }}</td>
                        <td>{{ rs.amount }} TL</td>
                        <td>
                            <a href="/order/deletefromcart/{{ shopcart.id }}">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}

                    <td colspan="5" ><b> Toplam alışveriş tutarı : {{ carttotal }} TL</b>
                    </tbody>
                </table>
            </div>
			</form>
        </div>
	</section> <!--/#cart_items-->

{% endblock %}

order/templates/shop_cart_list.html
{% extends "homebase.html" %}

{% block title %} shop cart  {% endblock %}

{% block body   %}
<h1>Shopcart index</h1>

            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
                {% endfor %}

            {% endif %}

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Product Name</th>
                <th>Sale Price</th>
                <th>Quantity</th>
                <th>Amount</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>


        {% for rs in shopcart %}
            <tr>
                <td>{{ rs.product.price }}</td>
                <td>{{ rs.id }}</td>
                <td>{{ rs.product.title }}</td>
                <td>{{ rs.quantity }}</td>
                <td>{{ rs.amount }} TL</td>
                <td>
                    <a href="/order/deletefromcart/{{ rs.id }}">Delete</a>
                </td>
            </tr>
        {% endfor %}

        <td colspan="5" ><b> toplam alışveriş tutarı :{{ carttotal }} TL</b>
        </tbody>
    </table>

        <div class="pull-right">
            <a href="/order/checkout" class="btn btn-default check_out">Check Out</a>
        </div>


{% endblock %}

order/templates/user_menu.html
<div class="">
    <li><a href="/user/profile"><i class="fa fa-user-o"></i>My Account </a> </li>
    <li><a href="/user/whislist"><i class="fa fa-user-o"></i>My Whislist </a> </li>
    <li><a href="/order/shopcart"><i class="fa fa-user-o"></i>Shop Cart </a> </li>
    <li><a href="/order/checkout"><i class="fa fa-user-o"></i> Checkout </a> </li>
    <li><a href="/order"><i class="fa fa-user-o"></i>Orders </a> </li>
    <li><a href="logout"><i class="fa fa-user-o"></i>Logout </a> </li>

</div>